### ISSUE TITLE
This addon caused fps loss & I'm unsure how to revert the changes

### ISSUE THREAD

**Issue by Thugli** [mrrosh/VanillaGraphicBoost#1]
Not necessarily an issue, as it's likely to be an issue on my end, but after installing this addon my average fps dropped from about 85 to 55. All variables have stayed the same between having 85 fps and now; location, add-ons, number of people around me, applications running in the background etc... and I have since uninstalled the addon and reset my in-game video settings but my fps remains around 55.

My concern is that is that this addon altered game files and these changes are persisting even after uninstalling the addon. Is there a default config file that I can just copy and paste to reset everything?

I don't fully understand how the addon works, so I could be wrong about what's going on.

**Comment by mrrosh** [comment]
All this addon does is to add a couple of console commands. You could try and delete your config.wtf file from the WTF folder.
